### PR TITLE
Slog based logging

### LINKED ISSUE #1164: Use golang's `slog` package
Go 1.21.0 introduced [`slog`](https://pkg.go.dev/golang.org/x/exp/slog) which provides structured logging through the standard library, therefore, this should be used to remove Uber's logging package dependency.

### PR DESCRIPTION
**Pull request by Exca-DK**
closes #1164, part of #1198 

The target is 1:1 of old formatting. Not possible with standard slog handlers

### CODE REVIEW

**Comment by joshklop** [comment]
Thank you for your effort there @Exca-DK. I don't think it's necessary to match the old format.

If we could get away with using `slog` defaults and remove everything but the interface (and possibly no-op implementation) from `utils/log.go`, that would be amazing.

**Comment by Exca-DK** [comment]
If we want to go with defaults then we will also need to remove the colors flag since slog doesn't support it.

**Comment by joshklop** [comment]
> If we want to go with defaults then we will also need to remove the colors flag since slog doesn't support it.

Thanks for pointing that out. It appears zap is [implementing](https://github.com/uber-go/zap/tree/master/exp/zapslog) its own slog handlers. Shall we continue using zap's nice features and let it handle the slog migration? cc @IronGauntlets

**Comment by Exca-DK** [comment]
Closing since the issue is closed too.

**Pull request closed without merging**
