### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by IronGauntlets**
## Description

This PR refactors the following:
- Removes rest server
- Removes juno cli

## Types of changes

- Refactoring (no functional changes, no api changes)

## Testing

**Requires testing**: No

## Documentation

**If this requires a documentation update, did you add one?** Yes

### CODE REVIEW

**Comment by tshakalekholoane** [comment]
Why are we moving public packages up a level?

**Comment by IronGauntlets** [comment]
There is no need for having a `pkg` package as explained [here](https://dave.cheney.net/tag/pkg).

**Comment by tshakalekholoane** [comment]
> the boilerplate of an empty pkg/ directory distracts from the more useful idiom of an internal/ directory.

As far as I am aware Git does not track empty directories. Am I missing something?

> a directory that exists only to hold other packages is a potential design smell.

I don't agree and I think the [current structure](https://github.com/golang-standards/project-layout) serves us better because we have a lot of non-Go components like the documentation website and having a pkg directory makes it easier for developers to make the distinction. In addition to that, I do not see any material benefit from adopting this change.

**Comment by IronGauntlets** [comment]
It is a matter of personal preference, if you feel strongly about keeping the current structure I am ok with that and I will drop the commit.

**Comment by tshakalekholoane** [comment]
I am in favour of keeping the current structure.

I am also wondering whether it would make sense to put `internal/` under `cmd/juno/` given we now have a single binary and those internal packages aren't shared anymore. What do you think about that?

**Comment by IronGauntlets** [comment]
Well based on the project layout you shared it should be kept separate. So I think let's stick with that.

**Review by tshakalekholoane — APPROVED** [review]
LGTM.

**Review by stdevMac — APPROVED** [review]

**Review by joshklop — CHANGES_REQUESTED** [review]
I think we need to delete the [`docs/docs/features/cli.mdx`](https://gojuno.xyz/docs/features/cli) file as well.

**Comment by IronGauntlets** [comment]
Done. Also deleted `docs/docs/features/rest.mdx` and updated the example in `config.mdx`.

**Review by joshklop — APPROVED** [review]

**Pull request merged**
