### PR TITLE
enhancement: viper.AutomaticEnv

### LINKED ISSUE #905: Allow Juno to be configured by using environment variables
So instead of using flags or config file, we should be able to use environment variables as configuration as well.

[see](https://pkg.go.dev/github.com/spf13/viper#AutomaticEnv) `viper.AutomaticEnv`

### PR DESCRIPTION
**Pull request by lazyfuhrer**
Closes #905

Allowed Juno to be configured by using environment variables using `viper.AutomaticEnv`

### CODE REVIEW

**Review by joshklop — CHANGES_REQUESTED** [review]
Maybe a bit overkill, but I think it would be worthwhile to add tests with environment variables (they would catch things like the panic mentioned below).

Also, I think we need to use `viper.SetEnvKeyReplacer` to ensure environment variables have a `JUNO_` prefix (avoids collisions with the user's existing environment).

**Comment by omerfirmak** [comment]
We need to set env prefix as well.

see https://pkg.go.dev/github.com/spf13/viper#SetEnvPrefix

se can simply set in to "JUNO"

**Comment by lazyfuhrer** [comment]
will keep ya posted 👍🏻

**Comment by omerfirmak** [comment]
Closing because of inactivity

**Pull request closed without merging**
