### PR TITLE
Add Tests for node/http.go

### PR DESCRIPTION
**Pull request by aminsato**
#1180 
Hi @joshklop 
I made test for node/http.go  relating to your issue.
Please review my PR
Thanks

### CODE REVIEW

**Review by joshklop — COMMENTED** [review]
I think the primary benefit of having tests for `node/http.go` is to make sure the servers can be run/shutdown properly. Since things like RPC methods are already well-tested in the `rpc` package, we don't need to test them all here.

See our previous tests for our http servers [here](https://github.com/NethermindEth/juno/blob/121d2ed77b4beb92c01ffab6d927455b68bf56f4/node/http/server_test.go) for inspiration.

**Comment by aminsato** [comment]
> I think the primary benefit of having tests for `node/http.go` is to make sure the servers can be run/shutdown properly. Since things like RPC methods are already well-tested in the `rpc` package, we don't need to test them all here.
> 
> See our previous tests for our http servers [here](https://github.com/NethermindEth/juno/blob/121d2ed77b4beb92c01ffab6d927455b68bf56f4/node/http/server_test.go) for inspiration.


@joshklop 
I Have made some changes.
Please review

**Comment by aminsato** [comment]
> I think the primary benefit of having tests for `node/http.go` is to make sure the servers can be run/shutdown properly. Since things like RPC methods are already well-tested in the `rpc` package, we don't need to test them all here.
> 
> See our previous tests for our http servers [here](https://github.com/NethermindEth/juno/blob/121d2ed77b4beb92c01ffab6d927455b68bf56f4/node/http/server_test.go) for inspiration.

Hi @joshklop

You forgot to review my PR

 Thanks for your time

**Review by joshklop — COMMENTED** [review]
We should have tests for every server (but not every method on every server). The purpose of these tests is to ensure we can make basic requests when the node is booted.

**Comment by omerfirmak** [comment]
Closing due to inactivity, feel free to reopen when it is ready to be reviewed.

**Comment by aminsato** [comment]
> Closing due to inactivity, feel free to reopen when it is ready to be reviewed.

### I have made some changes.


### please reopen the PR

**Comment by joshklop** [comment]
Hi @aminsato, thanks for taking the time to contribute to Juno. While these changes do test a portion of the `httpService`, we are looking for more extensive tests that give us confidence that all of the servers that we initialize in `node/http.go` will serve data properly. Because of that, we won't be merging this PR.

**Pull request closed without merging**
