### PR TITLE
Revert adding useless felt.Clone receiver

### PR DESCRIPTION
**Pull request by joshklop**

### CODE REVIEW

**Comment by omerfirmak** [comment]
Looks like `Clone()` was pretty handy when writing https://github.com/NethermindEth/juno/pull/1537?

**Comment by joshklop** [comment]
> Looks like Clone() was pretty handy when writing #1537?

True, but we can use `new(felt.Felt).Set(x)`, which maintains the convention that the caller should explicitly allocate. I forgot this existed when I implemented the `Clone` approach.

**Comment by omerfirmak** [comment]
> > Looks like Clone() was pretty handy when writing #1537?
> 
> True, but we can use `new(felt.Felt).Set(x)`, which maintains the convention that the caller should explicitly allocate. I forgot this existed when I implemented the `Clone` approach.

> which maintains the convention that the caller should explicitly allocate

I think Clone() still makes sense, because it they want a value copy they can just do `newFelt := *oldFeltPtr`, `newFelt := oldFelt`. Since felt.Felt is a simple type which doesnt store any references in it. 

To me, an explicit call to `Clone()` conveys the intent of actually doing a heap allocation.  

I would prefer `Clone()` over `new(felt.Felt).Set(x)` since it looks nicer and avoids repetition imo. Approving regardless, feel free to merge or close.

**Review by omerfirmak — APPROVED** [review]

**Comment by joshklop** [comment]
> I would prefer Clone() over new(felt.Felt).Set(x) since it looks nicer and avoids repetition imo.

I don't have much of a preference on the aesthetics, so I'll defer here.

**Pull request closed without merging**
