### PR TITLE
Replace Goerli2 network with Sepolia in the test TestEvents

### PR DESCRIPTION
**Pull request by stefanalfbo**
This PR is fixing the issue #1790, includes making a copy of the necessary testdata used from the `goerli2` directory to a new `sepolia` directory.

### CODE REVIEW

**Comment by rianhughes** [comment]
The test data should come from the Sepolia network, not the Goerli network. See issue https://github.com/NethermindEth/juno/pull/1793 for more details

**Review by rianhughes — APPROVED** [review]
Nice work. A nice follow on issue would be to update TestEvents in blockchain_test.go

**Comment by stefanalfbo** [comment]
Thank you, yes hopefully it will be pretty straight forward to update the TestEvents function in blockchain_test.go now.

**Comment by pnowosie** [comment]
@stefanalfbo Great work, thank you for contributing to juno! ❤️ 

Please note that previous PR (#1768) has spread rpc handlers tests into several file.
Kindly request to rebase your work onto current main and push again.

Thank you 🙏

**Comment by stefanalfbo** [comment]
Thanks @pnowosie, it should now be rebased on main.

**Pull request merged**
