### PR TITLE
Fail  Path suffix not match

### PR DESCRIPTION
**Pull request by liusanchuan**
Bug report #

### CODE REVIEW

**Comment by omerfirmak** [comment]
You are not building your bitsets right. They should be;

```
{ 
  parent: bitset.New(4).Set(0).Set(2),
  child: bitset.New(8).Set(2).Set(3).Set(4).Set(6), 
  want: bitset.New(3).Set(2), 
}
```

//0b 0101

right most bit here is called LSB, and is at index 0
left most bit here is called MSB, and is at index 3

**Comment by liusanchuan** [comment]
Hi @omerfirmak , Is the bit setting index is from tail to head? 
 `bitset.New(8).Set(2).Set(3).Set(4).Set(6), // is 0x01011100`
And If I want get the first index in path, I need to check path.Test(path.Len()-1), am I right?

**Comment by omerfirmak** [comment]
path.Test(path.Len()-1) tests MSB
path.Test(0) tests LSB

>  bitset.New(8).Set(2).Set(3).Set(4).Set(6), // is 0x01011100

correct

**Comment by liusanchuan** [comment]
Ohh, I got it, thanks a lot, 👍

**Pull request closed without merging**
