### PR TITLE
Update download link for Juno snapshots from dev to io in Readme file

### PR DESCRIPTION
**Pull request by AnavarKh**

### CODE REVIEW

**Review by derrix060 — CHANGES_REQUESTED** [review]
image

please check the links :)

**Comment by kirugan** [comment]
@AnavarKh any particular reason why you want to change these links?

**Comment by AnavarKh** [comment]
> @AnavarKh any particular reason why you want to change these links?

@kirugan We are using "nethermind.io"  DNS records for production env and  "nethermind.dev" is for dev|test environment. 
@derrix060 Every Link is working fine. Please verify. Thanks!

**Review by wojciechos — APPROVED** [review]

**Comment by AnkushinDaniil** [comment]
I used this script to check links.

``` shell
#!/bin/bash

BASE_DIR=$(pwd)

URL_REGEX="https?://[a-zA-Z0-9./?=_-]*"

check_url() {
    local url=$1
    curl -s --head --location --fail "$url" >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo "INVALID: $url"
    fi
}

find "$BASE_DIR" -type f -name "*.md" | while read -r file; do
    echo "Processing file: $file"
    grep -Eo "$URL_REGEX" "$file" | while read -r url; do
        check_url "$url"
    done
done
```

All updated links are valid.

**Review by derrix060 — APPROVED** [review]
links are working now ;)

**Comment by AnkushinDaniil** [comment]
Just checked again, one link is invalid
https://juno-snapshots.nethermind.io/sepolia/juno_sepolia_v0.11.7_66477.tar
@AnavarKh Can you please check?

**Pull request merged**
