### PR TITLE
Change to the network Sepoli and Sepolia-integration for the TestBlockWithTxHashes tests

### PR DESCRIPTION
**Pull request by stefanalfbo**
There is also new testdata files for the sepolia integration network that is used by the `TestBlockWithTxHashesV013`.

This PR is fixing the issue #1811

### CODE REVIEW

**Comment by pnowosie** [comment]
@stefanalfbo Great work, thank you for contributing to juno! ❤️ 

Please note that previous PR (#1768) has spread rpc handlers tests into several file.
Kindly request to rebase your work onto current main and push again.

Thank you 🙏

**Comment by stefanalfbo** [comment]
@pnowosie this one should also be rebased onto the current main now, BTW I like the refactoring of the rpc handlers :+1:

**Review by pnowosie — APPROVED** [review]
✅

**Comment by pnowosie** [comment]
This PR will be merge to main as a part of  #1861

**Pull request closed without merging**
