### PR TITLE
Remove v0.6 endpoints, added v0.8 endpoint

### PR DESCRIPTION
**Pull request by kirugan**

### CODE REVIEW

**Comment by derrix060** [comment]
some lint issues :)

**Comment by derrix060** [comment]
fyi I just rebased

**Comment by rianhughes** [comment]
Should we also update the readme / docs? Otherwise lgtm

**Review by rianhughes — APPROVED** [review]

**Comment by kirugan** [comment]
> Should we also update the readme / docs? Otherwise lgtm

let's do it in separate PR (starkware haven't merged the updates yet)

**Pull request merged**
