### PR TITLE
Create monitor

### PR DESCRIPTION
**Pull request by rianhughes**

### CODE REVIEW

**Comment by kirugan** [comment]
I think in general such things should be moved to middleware without required changes in any handler

**Comment by rianhughes** [comment]
> > I think in general such things should be moved to middleware without required changes in any handler
> 
> Yeap, should be fairly straightforward to collect all metrics related to RPC in `jsonrpc` package



> > I think in general such things should be moved to middleware without required changes in any handler
> 
> Yeap, should be fairly straightforward to collect all metrics related to RPC in `jsonrpc` package

So, something like jsonrpc this in https://github.com/NethermindEth/juno/pull/814/files?

**Comment by chichi13** [comment]
Has it been abandoned? No metrics added?

**Comment by IronGauntlets** [comment]
> Has it been abandoned? No metrics added?
No @chichi13, please have a look at #919

**Pull request closed without merging**
