### PR TITLE
mdbx implementation

### LINKED ISSUE #455: MDBX implementation
Implementation of MDBX wrapper using the [mdbx-go](https://github.com/torquem-ch/mdbx-go) bindings.

### PR DESCRIPTION
**Pull request by joshklop**
Closes #455 

## Description

Add the database interfaces and implementation.
- `Database`: contains all of Juno's tables (or "buckets"). This is represented by mdbx's "environment" struct, which manages the on-disk database file. 
- `Transaction`: creates buckets and opens cursors on buckets.
- `Cursor`: modifies the database, moves to keys in the database

We will probably need to add more functionality to the `Cursor` interface (e.g, `ForEach`, `PutMulti`, etc.) in the future, but it may make sense to add those incrementally rather than making this PR larger.

## Types of changes

- New feature (non-breaking change which adds functionality)
- Documentation Update

## Testing

**Requires testing**: Yes

**Did you write tests??**: Yes

## Documentation

**If this requires a documentation update, did you add one?** Yes: comments added where necessary

### CODE REVIEW

**Comment by joshklop** [comment]
Remaining to do:
* [ ] Add error types/functions
* [ ] Investigate mdbx flags and options to ensure we're using a robust configuration
* [ ] Add additional functionality to the cursor interface, if possible.

**Review by omerfirmak — APPROVED** [review]
Some descriptions to the interface members could be nice. It would help to guide people without much KV database experience. I had to go in to tests to understand what was happening.

**Review by omerfirmak — COMMENTED** [review]
and references for the future;

Unless you are building a feature incrementally, commits that change/remove/fix code that were introduced in the same PR should be squashed in to the original commit. This makes it so much easier to review the PR commit by commit. In this case "remove ..." commits fall in to this category.

unrelated commits should be in a separate PR. ie "format" here

**Comment by joshklop** [comment]
Thanks for the feedback and tips @omerfirmak! Much appreciated. I've updated the comments on the db interface and will aim for your suggested git conventions in the future.

**Review by omerfirmak — APPROVED** [review]
Feel free to merge at will.

Just a question, can we delete a key from a bucket? Or `Put`ing a `nil` to a key is essentially that?

**Pull request closed without merging**
