### PR TITLE
Switch to atomic

### PR DESCRIPTION
**Pull request by jelilat**
Closes https://github.com/NethermindEth/juno/issues/717

### CODE REVIEW

**Comment by IronGauntlets** [comment]
Did you run `make test-race`?

**Review by IronGauntlets — APPROVED** [review]
I ran `make test-race` and it didn't report any errors.

**Comment by jelilat** [comment]
> Did you run `make test-race`?

yes

**Comment by IronGauntlets** [comment]
@jelilat Please update the commit message. Give more context `Switch to atomic` is not sufficient

**Comment by IronGauntlets** [comment]
> This commit commit uses `atomic` instead of RWMutex to prevent race conditions in `sync_test` since it's more concise and simpler`

`commit` is mentioned twice. 

Also, the Commit subject line should be limited to 50 characters and the body should wrap at 72 characters as mentioned in the `The seven rules of a great Git commit message` section of [this](https://cbea.ms/git-commit/) article.

**Pull request merged**
