### PR TITLE
Add ErrCode constants to feeder

### PR DESCRIPTION
**Pull request by omerfirmak**
Towards #937

### CODE REVIEW

**Review by joshklop — APPROVED** [review]
Where did you find all of these?

**Comment by joshklop** [comment]
Actually just found [this](https://github.com/starkware-libs/cairo-lang/blob/54d7e92a703b3b5a1e07e9389608178129946efc/src/starkware/starknet/definitions/error_codes.py). Should we add the others?

**Comment by omerfirmak** [comment]
> Where did you find all of these?

Stole some of them from Pathfinder, the rest are the new errors from Write API

**Comment by omerfirmak** [comment]
> Actually just found [this](https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/starknet/definitions/error_codes.py). Should we add the others?

Hmm, let's either add them all or delete most of the existing ones as well and only keep the ones that we will check for write API. WDYT?

**Comment by joshklop** [comment]
Sounds good. I'm fine with both options.

**Comment by omerfirmak** [comment]
> delete most of the existing ones as well and only keep the ones that we will check for write API.

Let's go with this. I will close this PR for now and include this in the PR for #937

**Pull request closed without merging**
